// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDtTtwa_7FpvbjdRFVxpXGoptPzG-Ava9I',
    appId: '1:519338738024:web:5ecaf1416350693bb516dd',
    messagingSenderId: '519338738024',
    projectId: 'catpartners',
    authDomain: 'catpartners.firebaseapp.com',
    storageBucket: 'catpartners.appspot.com',
    measurementId: 'G-DQ2YPWYHB0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBs9drKqZhpP7tLfEky5GBnQzqmtwGtfyc',
    appId: '1:519338738024:android:fd06fc8eec9b5310b516dd',
    messagingSenderId: '519338738024',
    projectId: 'catpartners',
    storageBucket: 'catpartners.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAg46bvw8IYU-9QTsY9xP-qKrFCxfluj-Y',
    appId: '1:519338738024:ios:438e9e2a4e6023d5b516dd',
    messagingSenderId: '519338738024',
    projectId: 'catpartners',
    storageBucket: 'catpartners.appspot.com',
    iosBundleId: 'com.example.cpartners',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAg46bvw8IYU-9QTsY9xP-qKrFCxfluj-Y',
    appId: '1:519338738024:ios:85c94535c37c095fb516dd',
    messagingSenderId: '519338738024',
    projectId: 'catpartners',
    storageBucket: 'catpartners.appspot.com',
    iosBundleId: 'com.example.cpartners.RunnerTests',
  );
}
